namespace Model;

public enum Tags
{
    REQUEST_UPLOAD_VALIDATION = 100,
    RESPONSE_UPLOAD_VALIDATION,
    REQUEST_UPLOAD_FILE,
    RESPONSE_UPLOAD_FILE,
    REQUEST_DOWNLOAD_VALIDATION = 200,
    RESPONSE_DOWNLOAD_VALIDATION,
    REQUEST_DOWNLOAD_FILE,
    RESPONSE_DOWNLOAD_FILE,
    REQUEST_FILE_SEARCHING = 300,
    RESPONSE_FILE_SEARCHING,
    REQUEST_CHECK_FILE_EXIST,
    RESPONSE_CHECK_FILE_EXIST,
    REQUEST_DELETE_ALL_FILES = 400,
    RESPONSE_DELETE_ALL_FILES,
    REQUEST_ADVERTISE_UPLOAD_COMPLETION = 500,
    RESPONSE_ADVERTISE_UPLOAD_COMPLETION,
    REQUEST_FILE_SHARE_START = 600,
    RESPONSE_FILE_SHARE_START,
    REQUEST_UPDATE_FILE_SHARE_PROGRESS = 700,
    RESPONSE_UPDATE_FILE_SHARE_PROGRESS,
    REQUEST_FILE_CURRENT_SHARED_PROGRESS,
    RESPONSE_FILE_CURRENT_SHARED_PROGRESS,
    REQUEST_FILE_SHARE_END = 800,
    RESPONSE_FILE_SHARE_END,
}